# Copyright (c) 2014, Cédric Picard, Nicolas Loridon
# All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import yaml
import random
from exceptions import *


with open("./countries.yaml") as f:
    countries = yaml.load(f)


class MultiWorld:
    """
    This is a multiplayer-oriented world.
    """
    def __init__(self, viruses, first_countries):
        first_countries = (x.capitalize() for x in first_countries)
        self.viruses   = viruses

        self.infected  = { (v,c): 0 for v in self.viruses for c in countries }
        self.protected = { (v,c): 0 for v in self.viruses for c in countries }
        self.destroyed = { (v,c): 0 for v in self.viruses for c in countries }
        self.sane      = { (v,c): countries[c]["computers"]
                                    for v in self.viruses for c in countries }

        for each in zip(self.viruses, first_countries):
            self.infected[each[0], each[1]] += 1
            self.sane[each[0], each[1]]     -= 1
            each[0].target = each[1]


    def step(self):
        """
        Perform one turn of spreading
        """

        for v in self.viruses:
            v.age += 1
            inf_r  = v.spread * 0.001
            dest_r = v.danger * 0.001
            prot_r = v.detect * 0.001
            rent_r = v.rentab

            if inf_r < 0:
                inf_r = 0
            if dest_r < 0:
                dest_r = 0
            if prot_r < 0:
                prot_r = 0
            if rent_r < 0:
                rent_r = 0

            for c in countries:
                self.spread(v, c, inf_r, dest_r, prot_r, rent_r)


    def money(self, virus, country, rent_r):
        """
        Return the money generated by `virus' in `country'
        """
        return round(self.infected[virus, country]
                         / countries[country]["computers"]
                         * rent_r
                         * countries[country]["money"])


    def spread(self, virus, country, inf_r, dest_r, prot_r, rent_r):
        """
        Core of the game mechanics
        Manages the evolution of the infection in a country
        """
        target  = virus.target

        sane      = self.sane[virus, country]
        infected  = self.infected[virus, country]
        destroyed = self.destroyed[virus, country]
        protected = self.protected[virus, country]

        # Asymptotic limit counter-measure
        p_sane      = sane + 1000
        p_infected  = infected
        p_destroyed = destroyed
        p_protected = protected
        computers   = countries[country]["computers"]

        # Add some randomness to the values
        inf_r  *= (random.randint(1, 10) / 30)
        dest_r *= (random.randint(1, 10) / 30)
        prot_r *= (random.randint(1, 10) / 30)

        if target == None:
            pass
        elif target == country:
            inf_r *= 2.00
        else:
            inf_r *= 0.05

        sane -= round(inf_r * p_sane)
        if sane < 0:
            sane = 0

        infected += round(inf_r  * p_sane)
        infected -= round(dest_r * p_infected)
        infected -= round(prot_r * p_infected)
        if infected > computers:
            infected = computers

        destroyed += round(dest_r * infected)
        if destroyed > computers:
            destroyed = computers

        protected += round(prot_r * infected)
        if protected > computers:
            protected = computers

        self.sane[virus, country]      = sane
        self.infected[virus, country]  = infected
        self.protected[virus, country] = protected
        self.destroyed[virus, country] = destroyed
        virus.money += self.money(virus, country, rent_r)


    def upgrade(self, virus, immunity_rate, country_lst=None):
        """
        Apply a virus's upgrade given its immunity rate (between -1 and 1).
        One may specify a special list of countries, default is all.
        """
        if not country_lst:
            country_lst = countries

        for each in country_lst:
            self.sane[virus, each] += round((1 - immunity_rate)
                                                 * self.protected[virus, each])
            self.protected[virus, each]  = round(immunity_rate
                                                 * self.protected[virus, each])


    def repairs(self, virus, rate, country_lst=None):
        """
        Apply general reparations to a given rate of country's computers.
        One may specify a special list of countries, default is all.
        """
        if not country_lst:
            country_lst = countries

        for each in country_lst:
            self.sane[virus, each]      += round(rate
                                                 * self.destroyed[virus, each])
            self.destroyed[virus, each] -= round(rate
                                                 * self.destroyed[virus, each])


    def c_ratio(self, virus, country, *attributes):
        """
        Return the number of computer with the given attributes in the given
        country and the total of computer in this country
        """
        total = (self.sane[virus, country]
               + self.protected[virus, country]
               + self.infected[virus, country]
               + self.destroyed[virus, country])

        value = sum((self.__getattribute__(x)[virus, country]
                        for x in attributes))
        return value, total


    def print_country(self, virus, country=None):
        """
        return a string which describe the progression of the `virus' in a
        specific `country' or all of them if not specified
        """
        country = country or countries

        max_len = max([len(x) for x in country]) + 4

        state  = "Sane\n"
        state += "----\n"
        for each in country:
            state += each.ljust(max_len)
            state += " (%s\t/ %s)\n" % self.c_ratio(virus, each,
                                                    "sane", "protected")

        state += "\n"
        state += "Infected\n"
        state += "--------\n"
        for each in country:
            if self.infected[virus, each] != 0:
               state += each.ljust(max_len)
               state += " (%s\t/ %s)\n"% self.c_ratio(virus, each, "infected")

        state += "\n"
        state += "Destroyed\n"
        state += "---------\n"
        for each in country:
            if self.destroyed[virus, each] != 0:
                state += each.ljust(max_len)
                state += " (%s\t/ %s)\n" % self.c_ratio(virus, each, "destroyed")

        return state.rstrip('\n')

